export const PRIMARY_PLANNER_MODULE = "reading_plan.gui_api";
export const FALLBACK_PLANNER_MODULE = "reading_plan.cli";
export const PLANNER_MODULE_CANDIDATES = [
    PRIMARY_PLANNER_MODULE,
    FALLBACK_PLANNER_MODULE,
];

export const PYTHONPATH_SEGMENT = "src";
export const PYTHONPATH_KEY = "PYTHONPATH";
export const BRIDGE_LOG_PATH_KEY = "READING_PLAN_BRIDGE_LOG_PATH";
export const BRIDGE_REQUEST_ID_KEY = "READING_PLAN_BRIDGE_REQUEST_ID";

export const OUTPUT_PREVIEW_MAX_CHARS = 200;
export const LOG_TAIL_MAX_BYTES = 20_000;
export const LOG_TAIL_MAX_LINES = 120;

export const BRIDGE_HEARTBEAT_MS = 5_000;
export const DEFAULT_BRIDGE_TIMEOUT_MS = 300_000;
export const MIN_BRIDGE_TIMEOUT_MS = 1_000;
export const MAX_BRIDGE_TIMEOUT_MS = 3_600_000;
export const BRIDGE_TIMEOUT_MS_KEY = "READING_PLAN_BRIDGE_TIMEOUT_MS";
