import type { Book, Settings } from "@reading-schedule/contracts";

export const sampleSettings: Settings = {
  start_date: "2026-02-01",
  end_date: "2026-02-28",
  minutes_per_day: 30,
  wpm_base: 220,
  time_quantum_minutes: 15,
  max_sessions_per_day: 4,
  max_books_per_day: 2,
  max_blocks_per_book_per_day: 2,
  w_finish: 1,
  w_priority: 1,
  w_switch: 1,
  w_smooth: 1,
  minutes_by_weekday: {
    Mon: 30,
    Tue: 30,
    Wed: 30,
    Thu: 30,
    Fri: 30,
    Sat: 45,
    Sun: 45,
  },
  days_off: [],
  difficulty_multiplier: {
    "1": 1,
    "2": 1,
    "3": 1,
    "4": 1,
    "5": 1,
    "6": 1,
    "7": 1,
    "8": 1,
    "9": 1,
    "10": 1,
  },
};

export const sampleBooks: Book[] = [
  {
    book_id: "book-1",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    words_total: 95000,
    pages_total: null,
    pages_read: null,
    progress_percent: 0,
    priority: 2,
    difficulty: 3,
    min_blocks_per_session: 1,
    max_minutes_per_day: null,
    deadline: null,
    cover_url: "",
    cover_local_path: "",
    lookup_note: "",
  },
];
