class LinearExpr:
    def __add__(self, other: object) -> LinearExpr: ...
    def __radd__(self, other: object) -> LinearExpr: ...
    def __mul__(self, other: object) -> LinearExpr: ...
    def __rmul__(self, other: object) -> LinearExpr: ...
    def __sub__(self, other: object) -> LinearExpr: ...
    def __rsub__(self, other: object) -> LinearExpr: ...
    def __le__(self, other: object) -> object: ...
    def __ge__(self, other: object) -> object: ...
class IntVar(LinearExpr):
    pass
class CpModel:
    def new_int_var(self, lb: int, ub: int, name: str) -> IntVar: ...
    def new_bool_var(self, name: str) -> IntVar: ...
    def add(self, constraint: object) -> object: ...
    def add_hint(self, variable: IntVar, value: int) -> None: ...
    def maximize(self, objective: object) -> None: ...
class SatParameters:
    random_seed: int
    num_search_workers: int
    cp_model_presolve: bool
    stop_after_first_solution: bool
    max_time_in_seconds: float
class CpSolver:
    parameters: SatParameters

    def Solve(self, model: CpModel) -> int: ...  # noqa: N802
    def Value(self, variable: IntVar) -> int: ...  # noqa: N802
    def ObjectiveValue(self) -> float: ...  # noqa: N802
OPTIMAL: int
FEASIBLE: int
INFEASIBLE: int
MODEL_INVALID: int
UNKNOWN: int
