import { ALLOWED_CONSOLE_METHODS } from "../constants.mjs";

export const BASE_OPINIONATED_RULES = {
    "accessor-pairs": ["error", { getWithoutSet: false, setWithoutGet: true }],
    "array-callback-return": [
        "error",
        { allowImplicit: false, checkForEach: true },
    ],
    "block-scoped-var": "error",
    complexity: ["error", 10],
    "consistent-return": ["error", { treatUndefinedAsUnspecified: false }],
    curly: ["error", "all"],
    "default-case-last": "error",
    "default-param-last": "error",
    "dot-notation": ["error", { allowKeywords: true }],
    eqeqeq: ["error", "always"],
    "grouped-accessor-pairs": ["error", "getBeforeSet"],
    "guard-for-in": "error",
    "logical-assignment-operators": ["error", "always"],
    "max-classes-per-file": ["error", 1],
    "max-depth": ["error", 4],
    "max-lines": [
        "error",
        { max: 300, skipBlankLines: true, skipComments: true },
    ],
    "max-lines-per-function": [
        "error",
        { IIFEs: true, max: 80, skipBlankLines: true, skipComments: true },
    ],
    "max-nested-callbacks": ["error", 3],
    "max-params": ["error", 4],
    "max-statements-per-line": ["error", { max: 1 }],
    "new-cap": "error",
    "no-alert": "error",
    "no-array-constructor": "error",
    "no-caller": "error",
    "no-console": ["error", { allow: ALLOWED_CONSOLE_METHODS }],
    "no-constructor-return": "error",
    "no-duplicate-imports": ["error", { includeExports: true }],
    "no-else-return": ["error", { allowElseIf: false }],
    "no-empty-function": "error",
    "no-implicit-coercion": [
        "error",
        {
            boolean: false,
            disallowTemplateShorthand: true,
            number: true,
            string: true,
        },
    ],
    "no-implicit-globals": "error",
    "no-implied-eval": "error",
    "no-inner-declarations": ["error", "functions"],
    "no-lonely-if": "error",
    "no-loop-func": "error",
    "no-multi-assign": "error",
    "no-new-wrappers": "error",
    "no-param-reassign": ["error", { props: true }],
    "no-promise-executor-return": "error",
    "no-return-assign": ["error", "always"],
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-shadow": "error",
    "no-ternary": "error",
    "no-unreachable-loop": "error",
    "no-unused-expressions": [
        "error",
        {
            allowShortCircuit: false,
            allowTaggedTemplates: false,
            allowTernary: false,
        },
    ],
    "no-use-before-define": [
        "error",
        { classes: true, functions: false, variables: true },
    ],
    "no-useless-call": "error",
    "no-useless-computed-key": "error",
    "no-useless-concat": "error",
    "no-useless-constructor": "error",
    "no-useless-rename": "error",
    "no-useless-return": "error",
    "no-void": ["error", { allowAsStatement: false }],
    "object-shorthand": ["error", "always"],
    "one-var": ["error", "never"],
    "operator-assignment": ["error", "always"],
    "prefer-arrow-callback": [
        "error",
        { allowNamedFunctions: false, allowUnboundThis: true },
    ],
    "prefer-const": "error",
    "prefer-exponentiation-operator": "error",
    "prefer-numeric-literals": "error",
    "prefer-object-has-own": "error",
    "prefer-object-spread": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    radix: ["error", "always"],
    "require-await": "error",
    "symbol-description": "error",
    yoda: ["error", "never"],
};
