import { ALLOWED_CONSOLE_METHODS } from "../constants.mjs";

export const BASE_OPINIONATED_RULES = {
  "accessor-pairs": ["error", { setWithoutGet: true, getWithoutSet: false }],
  "array-callback-return": ["error", { allowImplicit: false, checkForEach: true }],
  "block-scoped-var": "error",
  "consistent-return": ["error", { treatUndefinedAsUnspecified: false }],
  complexity: ["error", 10],
  curly: ["error", "all"],
  "default-case-last": "error",
  "default-param-last": "error",
  eqeqeq: ["error", "always"],
  "guard-for-in": "error",
  "no-alert": "error",
  "no-array-constructor": "error",
  "no-caller": "error",
  "no-constructor-return": "error",
  "no-else-return": ["error", { allowElseIf: false }],
  "no-empty-function": "error",
  "no-implied-eval": "error",
  "no-inner-declarations": ["error", "functions"],
  "no-loop-func": "error",
  "no-multi-assign": "error",
  "no-param-reassign": ["error", { props: true }],
  "no-promise-executor-return": "error",
  "no-return-assign": ["error", "always"],
  "no-self-compare": "error",
  "no-shadow": "error",
  "no-ternary": "error",
  "no-unreachable-loop": "error",
  "no-unused-expressions": [
    "error",
    { allowShortCircuit: false, allowTernary: false, allowTaggedTemplates: false },
  ],
  "no-use-before-define": ["error", { functions: false, classes: true, variables: true }],
  "no-useless-call": "error",
  "no-useless-computed-key": "error",
  "no-useless-concat": "error",
  "no-useless-constructor": "error",
  "no-useless-rename": "error",
  "no-useless-return": "error",
  "no-void": ["error", { allowAsStatement: false }],
  "prefer-promise-reject-errors": "error",
  "require-await": "error",
  "dot-notation": ["error", { allowKeywords: true }],
  "grouped-accessor-pairs": ["error", "getBeforeSet"],
  "logical-assignment-operators": ["error", "always"],
  "max-classes-per-file": ["error", 1],
  "max-depth": ["error", 4],
  "max-lines": ["error", { max: 200, skipBlankLines: true, skipComments: true }],
  "max-lines-per-function": [
    "error",
    { max: 80, skipBlankLines: true, skipComments: true, IIFEs: true },
  ],
  "max-nested-callbacks": ["error", 3],
  "max-params": ["error", 4],
  "max-statements-per-line": ["error", { max: 1 }],
  "new-cap": "error",
  "no-console": ["error", { allow: ALLOWED_CONSOLE_METHODS }],
  "no-duplicate-imports": ["error", { includeExports: true }],
  "no-implicit-coercion": [
    "error",
    { boolean: false, number: true, string: true, disallowTemplateShorthand: true },
  ],
  "no-implicit-globals": "error",
  "no-lonely-if": "error",
  "no-negated-condition": "error",
  "no-new-wrappers": "error",
  "no-script-url": "error",
  "object-shorthand": ["error", "always"],
  "one-var": ["error", "never"],
  "operator-assignment": ["error", "always"],
  "prefer-arrow-callback": [
    "error",
    { allowNamedFunctions: false, allowUnboundThis: true },
  ],
  "prefer-const": "error",
  "prefer-exponentiation-operator": "error",
  "prefer-numeric-literals": "error",
  "prefer-object-has-own": "error",
  "prefer-object-spread": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "prefer-template": "error",
  radix: ["error", "always"],
  "symbol-description": "error",
  yoda: ["error", "never"],
};
