[package]
name = "bartleby_app"
version = "0.1.4-alpha"
description = "Bartleby is a reading schedule optimizer"
authors = ["uripper"]
default-run = "bartleby_app"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "bartleby_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
base64 = "0.22.1"
chrono = { version = "0.4.45", features = ["clock"] }
directories = "6.0.0"
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png", "webp"] }
reqwest = { version = "0.13.4", features = ["json"] }
rusqlite = { version = "0.39.0", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.10.9"
tauri = { version = "2.11.5", features = ["protocol-asset"] }
tauri-plugin-opener = "=2.5.4"
tauri-plugin-process = "=2.3.1"
urlencoding = "2.1.3"
uuid = { version = "1.24.0", features = ["v4"] }

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-updater = "=2.10.1"
